version: '3'
services:
  es1:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
    ports:
      - 9200:9200
#  kinana not work on arm64
#  kibana1:
#    image: kibana:7.12.0
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_HOSTS: http://es1:9200